apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecharts
  namespace: minecharts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecharts
  template:
    metadata:
      labels:
        app: minecharts
    spec:
      serviceAccountName: minecharts
      containers:
        - name: minecharts
          image: ghcr.io/zent0x/minecharts:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
