apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecharts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecharts
  template:
    metadata:
      labels:
        app: minecharts
    spec:
      serviceAccountName: minecharts-sa
      containers:
      - name: minecharts
        image: ghcr.io/zent0x/minecharts:latest
        ports:
        - containerPort: 8080
