apiVersion: v1
kind: Namespace
metadata:
  name: minecharts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecharts
  namespace: minecharts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minecharts
  namespace: minecharts
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minecharts
  namespace: minecharts
subjects:
  - kind: ServiceAccount
    name: minecharts
    namespace: minecharts
roleRef:
  kind: Role
  name: minecharts
  apiGroup: rbac.authorization.k8s.io
