name: Build Docker Image for Dev

on:
  push:
    branches: [dev]

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Go with caching using magnetikonline/golang-with-cache@v5.
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod

      # Set up Docker Buildx.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry.
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image for Dev.
      # The image is tagged with both a commit-specific tag and the fixed tag "dev-latest".
      - name: Build and push Docker image for Dev
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/zent0x/minecharts:dev-${{ github.sha }}
            ghcr.io/zent0x/minecharts:dev-latest
