name: Build Docker Image for Dev

on:
  push:
    branches: [dev]

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository.
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go.
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # Cache Go build and module dependencies.
      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      # Download Go dependencies.
      - name: Download Go dependencies
        run: go mod download

      # Set up Docker Buildx.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry.
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image for Dev.
      # The image is tagged with both a commit-specific tag and the fixed tag "dev-latest".
      - name: Build and push Docker image for Dev
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/zent0x/minecharts:dev-${{ github.sha }}
            ghcr.io/zent0x/minecharts:dev-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
