name: Release and Build Docker Image for Main

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository.
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache Node modules for semantic-release.
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Set up Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install Node dependencies.
      - name: Install dependencies
        run: npm install

      # Run semantic-release to analyze commits and publish a new version.
      - name: Run semantic-release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Retrieve the new version from package.json.
      - name: Get new version
        id: get_version
        run: echo "::set-output name=version::$(node -p \"require('./package.json').version\")"

      # Cache Go modules to speed up the build.
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            $(go env GOPATH)/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Set up Docker Buildx (BuildKit) for advanced build options.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to GitHub Container Registry.
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image with two tags: latest and the version number.
      - name: Build and push Docker image for Main
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/zent0x/minecharts:latest
            ghcr.io/zent0x/minecharts:${{ steps.get_version.outputs.version }}
